version: '3.1'

services:
# password doesn't work this way... there is a work around, but for now:
#docker run -d -p 9000:9000 --restart always -v /var/run/docker.sock:/var/run/docker.sock -v /opt/portainer:/data portainer/portainer
#  portainer:
#    ports:
#      - '9000:9000'
#    restart: always
#    volumes:
#        - '/var/run/docker.sock:/var/run/docker.sock'
#        - '/opt/portainer:/data'
#    image: portainer/portainer

  employeeappapi:
    build: .
    image: jdell64/employee-app-api
    restart: always
    container_name: employee-app-api
    ports:
      - 8182:8080
    working_dir: /opt/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: employee-app-db #rename
#    ports:  # for demo/debug purpose only
#      - 27018:27017
    volumes:
      - $HOME/data/employee-app-data:/data/db
      - $HOME/data/employee-app-bkp:/data/bkp
    restart: always

  employeeweb:
    build: ./frontend
    restart: always
    container_name: employee-app-web
    image: jdell64/employee-app-web
    ports:
      - 4000:4000
    working_dir: /app
    depends_on:
      - employeeappapi
    links:
      - employeeappapi
