version: '3.1'

services:
  employeeapp:
    build: .
    # image: registry.gitlab.com/idgst/employee-app-demo:latest
    restart: always
    container_name: employeeapp
    ports:
      - 8182:8080
    working_dir: /opt/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: employee-app
    ports:  # for demo/debug purpose only
      - 27018:27017
    volumes:
      - $HOME/data/employee-app-data:/data/db
      - $HOME/data/employee-app-bkp:/data/bkp
    restart: always