version: '3.1'

services:
  employeeappapi: #rename
    build: .
    # image: registry.gitlab.com/idgst/employee-app-demo:latest
    restart: always
    container_name: employee-app-api
    ports:
      - 8182:8080
    working_dir: /opt/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: employee-app-db #rename
    ports:  # for demo/debug purpose only
      - 27018:27017
    volumes:
      - $HOME/data/employee-app-data:/data/db
      - $HOME/data/employee-app-bkp:/data/bkp
    restart: always

  employeeweb:
    build: ./frontend
    restart: always
    container_name: employee-app-web
    ports:
      - 4000:4000
    working_dir: /app
    depends_on:
      - employeeappapi
    links:
      - employeeappapi
